/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Descuento;
import Logica.Exceptions.PersonaException;
import Logica.Exceptions.SimuladorException;
import Logica.Persona;
import Logica.Recargo;
import Logica.Simulador;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() { //inicio
        initComponents();
        this.showNoIniciada(); //oculta elementos antes de apretar calcular
        this.setLocationRelativeTo(null); //centra la ventana (Jframe) en la pantalla cuando se crea
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rb_jubilado_no = new javax.swing.JRadioButton();
        rb_jubilado_si = new javax.swing.JRadioButton();
        rb_trabajando_si = new javax.swing.JRadioButton();
        rb_trabajando_no = new javax.swing.JRadioButton();
        rb_enfermedad_si = new javax.swing.JRadioButton();
        rb_enfermedad_no = new javax.swing.JRadioButton();
        txt_monto_cuenta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_aporte_voluntario = new javax.swing.JTextField();
        bt_nueva_simulacion = new javax.swing.JButton();
        bt_calcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panel_recargos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_recargos = new javax.swing.JList<>();
        panel_descuentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_descuentos = new javax.swing.JList<>();
        lb_esperanza_vida_valor = new javax.swing.JLabel();
        lb_no_iniciada = new javax.swing.JLabel();
        lb_valor_cuota = new javax.swing.JLabel();
        lb_valor_cuota_valor = new javax.swing.JLabel();
        lb_esperanza_vida1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("en Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 20));

        jLabel2.setText("Tiene enfermedad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 20));

        jLabel4.setText("Monto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 20));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 24, 270, 30));

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        jPanel1.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, 30));

        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 60, 20));

        jLabel6.setText("Es jubilado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 60, 20));

        jLabel7.setText("Esta trabajando");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 90, 20));

        buttonGroup1.add(rb_jubilado_no);
        rb_jubilado_no.setText("NO");
        rb_jubilado_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_jubilado_noActionPerformed(evt);
            }
        });
        jPanel1.add(rb_jubilado_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        buttonGroup1.add(rb_jubilado_si);
        rb_jubilado_si.setText("SI");
        rb_jubilado_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_jubilado_siActionPerformed(evt);
            }
        });
        jPanel1.add(rb_jubilado_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        buttonGroup2.add(rb_trabajando_si);
        rb_trabajando_si.setText("SI");
        rb_trabajando_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_trabajando_siActionPerformed(evt);
            }
        });
        jPanel1.add(rb_trabajando_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        buttonGroup2.add(rb_trabajando_no);
        rb_trabajando_no.setText("NO");
        rb_trabajando_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_trabajando_noActionPerformed(evt);
            }
        });
        jPanel1.add(rb_trabajando_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        buttonGroup3.add(rb_enfermedad_si);
        rb_enfermedad_si.setText("SI");
        rb_enfermedad_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_enfermedad_siActionPerformed(evt);
            }
        });
        jPanel1.add(rb_enfermedad_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        buttonGroup3.add(rb_enfermedad_no);
        rb_enfermedad_no.setText("NO");
        rb_enfermedad_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_enfermedad_noActionPerformed(evt);
            }
        });
        jPanel1.add(rb_enfermedad_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        txt_monto_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_monto_cuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_monto_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 30));

        jLabel12.setText("Edad");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 480, 160));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulacion"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Aporte ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 20));

        jLabel9.setText("Voluntario");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 20));

        jLabel10.setText("Voluntario");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 20));

        jLabel11.setText("Aporte ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        txt_aporte_voluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aporte_voluntarioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_aporte_voluntario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 30));

        bt_nueva_simulacion.setText("Nueva Simulación");
        bt_nueva_simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nueva_simulacionActionPerformed(evt);
            }
        });
        jPanel2.add(bt_nueva_simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });
        jPanel2.add(bt_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 480, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_recargos.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos"));
        panel_recargos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(list_recargos);

        panel_recargos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 80));

        jPanel3.add(panel_recargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 110));

        panel_descuentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos"));
        panel_descuentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(list_descuentos);

        panel_descuentos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 80));

        jPanel3.add(panel_descuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, 110));

        lb_esperanza_vida_valor.setText("---");
        jPanel3.add(lb_esperanza_vida_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, 20));

        lb_no_iniciada.setText("Simulación no iniciada");
        jPanel3.add(lb_no_iniciada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 190, 20));

        lb_valor_cuota.setText("Valor Cuota");
        jPanel3.add(lb_valor_cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 20));

        lb_valor_cuota_valor.setText("---");
        jPanel3.add(lb_valor_cuota_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 60, 20));

        lb_esperanza_vida1.setText("Esperanza de vida");
        jPanel3.add(lb_esperanza_vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 480, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_aporte_voluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aporte_voluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aporte_voluntarioActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void rb_jubilado_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_jubilado_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_jubilado_noActionPerformed

    private void rb_jubilado_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_jubilado_siActionPerformed

    }//GEN-LAST:event_rb_jubilado_siActionPerformed

    private void rb_trabajando_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_trabajando_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_trabajando_siActionPerformed

    private void rb_trabajando_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_trabajando_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_trabajando_noActionPerformed

    private void rb_enfermedad_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_enfermedad_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_enfermedad_siActionPerformed

    private void rb_enfermedad_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_enfermedad_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_enfermedad_noActionPerformed

    private void txt_monto_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_monto_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_monto_cuentaActionPerformed

    private void bt_nueva_simulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nueva_simulacionActionPerformed
        this.limpiarFormulario();
        this.showNoIniciada();
    }//GEN-LAST:event_bt_nueva_simulacionActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        try {
            
            Persona p = new Persona();
            p.setNombre(txt_nombre.getText());
            p.setEdad(Integer.parseInt(txt_edad.getText().toString()));
            p.setMonto_en_cuenta(Integer.parseInt(txt_monto_cuenta.getText().toString()));
            p.setEs_jubilado(rb_jubilado_si.isSelected());
            p.setEsta_trabajando(rb_trabajando_si.isSelected());
            p.setTiene_enfermedad_base(rb_enfermedad_si.isSelected());

            Simulador s = new Simulador();
            s.setCliente(p);// Asignar el cliente al simulador
            s.setMonto_aporte_voluntario(Integer.parseInt(txt_aporte_voluntario.getText().toString()));

            
            Double valor_cuota= s.calcularValorCuota(); // Asigna el valor retornado a una variable
            lb_valor_cuota_valor.setText(Double.toString(valor_cuota));// Actualizar con valor cuota calculado(Double)
            //lb_valor_cuota_valor.setText(s.calcularValorCuota().toString());// Actualizar con valor cuota calculado (SOlO SIRVE CON INTEGER)
            lb_esperanza_vida_valor.setText(s.getEsperanza_de_vida().toString()); // Actualizar con esperanza de vida
            if (s.verificarFirmarAcuerdoRecargos()) {
                JOptionPane.showMessageDialog(this, "Debe firmar acuerdo de recargos", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }

            // Actualizar JList de descuentos
            DefaultListModel <Descuento> descuentoModel = new DefaultListModel();
            for (Descuento de : s.getLista_descuentos()) {
                descuentoModel.addElement(de);//pasamos el objeto completo
            }
            list_descuentos.setModel(descuentoModel);

            // Actualizar JList de recargos
            DefaultListModel <Recargo>recargoModel = new DefaultListModel();
            for (Recargo re : s.getLista_recargos()) {
                recargoModel.addElement(re);//pasamos el objeto completo
            }
            list_recargos.setModel(recargoModel);
            this.showIniciada();
        } catch (PersonaException ex) {
            // Captura la excepción personalizada si la edad o el nombre son incorrectos
            //Segun cual captura lanza un mensaje u otro.
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            // Captura la excepción si el texto ingresado no es un número (exception estandar de Java)
            JOptionPane.showMessageDialog(this, "La edad debe ser un numero valido.", "Error en formato", JOptionPane.ERROR_MESSAGE);
        } catch (SimuladorException ex) {
            // Captura la excepción personalizada si la edad o el nombre son incorrectos
            //Segun cual captura lanza un mensaje u otro.
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_calcularActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void showNoIniciada() { //no mostrar panel resultado
        this.lb_no_iniciada.setVisible(false);
        this.lb_esperanza_vida_valor.setVisible(false);
        this.lb_valor_cuota.setVisible(false);
        this.lb_valor_cuota_valor.setVisible(false);
        this.panel_recargos.setVisible(false);
        this.panel_descuentos.setVisible(false);
        this.lb_no_iniciada.setVisible(true);
    }

    private void showIniciada() { //mostrar panel resultado
        this.lb_no_iniciada.setVisible(true);
        this.lb_esperanza_vida_valor.setVisible(true);
        this.lb_valor_cuota.setVisible(true);
        this.lb_valor_cuota_valor.setVisible(true);
        this.panel_recargos.setVisible(true);
        this.panel_descuentos.setVisible(true);
        this.lb_no_iniciada.setVisible(false);
    }

    private void limpiarFormulario() { //limpia los textos y radio button
        this.txt_nombre.setText("");
        this.txt_edad.setText("");
        this.txt_monto_cuenta.setText("");
        this.txt_aporte_voluntario.setText("");
        this.buttonGroup1.clearSelection();
        this.buttonGroup2.clearSelection();
        this.buttonGroup3.clearSelection();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_nueva_simulacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_esperanza_vida1;
    private javax.swing.JLabel lb_esperanza_vida_valor;
    private javax.swing.JLabel lb_no_iniciada;
    private javax.swing.JLabel lb_valor_cuota;
    private javax.swing.JLabel lb_valor_cuota_valor;
    private javax.swing.JList<Descuento> list_descuentos;
    private javax.swing.JList<Recargo> list_recargos;
    private javax.swing.JPanel panel_descuentos;
    private javax.swing.JPanel panel_recargos;
    private javax.swing.JRadioButton rb_enfermedad_no;
    private javax.swing.JRadioButton rb_enfermedad_si;
    private javax.swing.JRadioButton rb_jubilado_no;
    private javax.swing.JRadioButton rb_jubilado_si;
    private javax.swing.JRadioButton rb_trabajando_no;
    private javax.swing.JRadioButton rb_trabajando_si;
    private javax.swing.JTextField txt_aporte_voluntario;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_monto_cuenta;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
